stages:
  download_data:
    cmd: ./stages/01_download.sh
    deps:
    - stages/01_download.sh
    outs:
    - download/
  make_parquet:
    cmd: Rscript stages/02_build.R
    deps:
    - stages/02_build.R
    - download/
    outs:
    - brick/
